MDCT-1822: Design Feedback Tweeks
CMSgov/mdct-mcr pull request #3188
Opened 2022-07-26 11:29 UTC by ntsummers1

## Description
Fixes [MDCT-1822](https://qmacbis.atlassian.net/browse/MDCT-1822). MCR: The Padded Edition

Fixes:
* Increase outside margin of the header to 36px (2.25rem)

* Increase outside margin of the footer to 36px (2.25rem)

* Remove Autosave State from subheader

* Decrease size of field hint text to 14px.

### How to test
./dev local
Check out the header in the desktop view and any of the form pages!

### Changed Dependencies

## Code author checklist
- [x] I have performed a self-review of my code
- [x] I have added [thorough](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2914025525/Test+Suite+and+Testing+Research) tests
- [x] I have added analytics, if necessary
- [x] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-07-26 14:12 UTC, gmrabian requested changes
Looks good! I have two asks:

1. Convert the px to rem, just to keep with the repo's standard
2. The form runner and the admin banner is now misaligned with the header/footer
main: 
<img width="111" alt="Screen Shot 2022-07-26 at 7 07 06 AM" src="https://user-images.githubusercontent.com/57802560/181026673-ab0b47d9-d19c-4e73-88d7-63b0fd65f304.png">
<img width="91" alt="Screen Shot 2022-07-26 at 7 07 01 AM" src="https://user-images.githubusercontent.com/57802560/181026678-1d137204-85cd-4697-98ae-80080d8f7d12.png">

This branch:
<img width="66" alt="Screen Shot 2022-07-26 at 7 07 19 AM" src="https://user-images.githubusercontent.com/57802560/181026753-583c507b-fa43-4647-ba91-f366e4cc0a48.png">
<img width="84" alt="Screen Shot 2022-07-26 at 7 07 14 AM" src="https://user-images.githubusercontent.com/57802560/181026756-b9142768-f802-4d72-8a3b-19cfdf6cdbfa.png">
<img width="122" alt="Screen Shot 2022-07-26 at 7 11 09 AM" src="https://user-images.githubusercontent.com/57802560/181027017-ea35102b-bace-49c0-95cb-6a1ef94ab712.png">
<img width="185" alt="Screen Shot 2022-07-26 at 7 11 26 AM" src="https://user-images.githubusercontent.com/57802560/181027090-ab40f338-988d-4066-a169-5f1b6d5fe16e.png">

2022-07-26 16:00 UTC, ntsummers1 commented
Asking design how to handle the subbanner now not being aligned. Moving the header also misaligns the side nav here too.

2022-07-26 17:44 UTC, gmrabian commented on services/ui-src/src/components/menus/Sidebar.tsx
> +        marginLeft: "-2.3rem",
This one snuck through!

2022-07-26 17:48 UTC, ntsummers1 commented on services/ui-src/src/components/menus/Sidebar.tsx
> +        marginLeft: "-2.3rem",
Good catch! Fixed

2022-07-26 17:49 UTC, ntsummers1 commented
> Asking design how to handle the subbanner now not being aligned. Moving the header also misaligns the side nav here too.

Design approved

2022-07-27 16:19 UTC, gmrabian commented
Awaiting design feedback on tablet/mobile sidebar misaligned with header/footer

2022-07-27 16:25 UTC, ntsummers1 commented
Met with Design
- Shrank desktop padding to 2rem
- Aligned all main content and side nav content to same padding as header and footer on mobile and desktop

2022-07-27 16:27 UTC, gmrabian approved these changes
Sweet, sweet alignment

2022-07-27 16:42 UTC, merged