[MDCT-1868] Section D: Encounter Data
CMSgov/mdct-mcr pull request #3576
Opened 2022-08-23 15:30 UTC by juliuscaesar

## Description
Adds Section D: Encounter Data. Closes [MDCT-1868](https://qmacbis.atlassian.net/browse/MDCT-1868)

### How to test
http://localhost:3000/mcpar/plan-level-indicators/encounter-data-report

### Changed Dependencies
N/A

## Code author checklist
- [x] I have performed a self-review of my code
- [x] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [x] I have added analytics, if necessary
- [x] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-08-23 17:46 UTC, braxex requested changes
Minor changes requested.

2022-08-23 17:46 UTC, braxex commented on services/ui-src/src/forms/mcpar/dedr/dedr.json
> +          "mask": "comma-separated"
No mask for now. Will be adding a percentage mask later. Applies to `dedr-2` and `dedr-3`.

Also need to make the fields disabled so users cannot enter data.

```suggestion
          "disabled": true
```

2022-08-23 17:48 UTC, gmrabian approved these changes

2022-08-23 21:51 UTC, braxex requested changes
Super close. Everything is breaking because of some commas in `dedr.json`. Sometimes the littlest things are the most important to check run locally before pushing. 😆

2022-08-23 21:51 UTC, braxex commented on services/ui-src/src/forms/mcpar/dedr/dedr.json
> +          "hint": "What percent of the plan’s encounter data file submissions (submitted during the reporting period) met state requirements for timely submission?</br>If the state has not yet receiv
Trailing comma here makes the JSON invalid and breaks everything. Same thing for the other `hint` below.

2022-08-24 22:41 UTC, braxex approved these changes

2022-08-25 14:26 UTC, merged