[MDCT-423] Section D: Program Characteristics
CMSgov/mdct-mcr pull request #3577
Opened 2022-08-23 15:30 UTC by juliuscaesar

## Description
Adds Section D: Plan-Level Program Characteristics & Enrollment. Closes [MDCT-423](https://qmacbis.atlassian.net/browse/MDCT-423)

### How to test
http://localhost:3000/mcpar/plan-level-indicators/program-characteristics

### Changed Dependencies
N/A

## Code author checklist
- [x] I have performed a self-review of my code
- [x] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [x] I have added analytics, if necessary
- [x] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-08-23 17:50 UTC, gmrabian approved these changes

2022-08-23 18:00 UTC, braxex requested changes
Minor changes requested.

You'll need to add styles for the `ul` to `Form.tsx` like this:
![Screen Shot 2022-08-23 at 12 58 12](https://user-images.githubusercontent.com/27705928/186231151-04527cd8-04a7-4d26-8d2c-742ccd03b08d.png)

2022-08-23 18:00 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpc/dpc.json
> +          "hint": "Automatically calculated. Sum of plan enrollment (within the specific program) as a percentage of the state's total Medicaid enrollment.",
Needs "numerator" and "denominator" bullets, like this. Applies to both `dpc-2` and `dpc-3`.

```suggestion
          "hint": "<p>Automatically calculated. Sum of plan enrollment (within the specific program) as a percentage of the state's total Medicaid enrollment.</p><ul><li>first bullet point</li><li>second bullet point</li></ul>",
```

2022-08-23 18:00 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpc/dpc.json
> +          "mask": "comma-separated",
Remove mask for now. Will make percentage mask later. Applies to both `dpc-2` and `dpc-3`.
```suggestion
```

2022-08-23 22:27 UTC, braxex requested changes

2022-08-23 22:27 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpc/dpc.json
> +          "hint": "<p>Automatically calculated. Sum of plan enrollment (within the specific program) as a percentage of the state's total Medicaid enrollment.</p><ul><li>Numerator: Plan enrollment (D
The nested `<ul>` is not necessary -- just the numerator and denominator. Same comment for `hint` below.

2022-08-24 22:39 UTC, braxex approved these changes

2022-08-25 14:23 UTC, merged