dpi
CMSgov/mdct-mcr pull request #3607
Opened 2022-08-25 16:29 UTC by juliuscaesar

## Description

### How to test

### Changed Dependencies

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-08-25 21:05 UTC, scwambach approved these changes

2022-08-26 13:49 UTC, gmrabian requested changes
Missing the question 10 label and hint text
<img width="285" alt="Screen Shot 2022-08-26 at 7 48 47 AM" src="https://user-images.githubusercontent.com/57802560/186918454-40c9fb23-2d5b-4317-862a-a927e437ddce.png">
<img width="361" alt="Screen Shot 2022-08-26 at 7 49 10 AM" src="https://user-images.githubusercontent.com/57802560/186918498-f29e5c19-c6b8-4546-9508-d34c14cc6c04.png">

2022-08-26 13:50 UTC, braxex requested changes
Just a couple changes needed.

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.json
> +                }
Well these are a super weird case, aren't they? After going back and forth a bunch, I think we should make the IDs for these 3 `dpi-7`s `dpi-7a`, `dpi-7b`, and `dpi-7c` to differentiate them from true options/choices and make it clear they are their own fields.

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.json
> +                  "id": "dpi-7-o1",
```suggestion
                  "id": "dpi-7a",
```

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.json
> +                  "id": "dpi-7-o2",
```suggestion
                  "id": "dpi-7b",
```

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.json
> +                  "id": "dpi-7-o3",
```suggestion
                  "id": "dpi-7c",
```

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.json
> +          "hint": "Describe the plan’s latest annual overpayment recovery report submitted to the state as required under 42 CFR 438.608(d)(3).</p>Include, for example, the following information:<ul>
Right now with no opening `p` tag it renders like this:

![Screen Shot 2022-08-26 at 08 45 28](https://user-images.githubusercontent.com/27705928/186917964-9e98a570-b480-467c-9666-6873d8d66be0.png)

Suggest either adding an opening `<p>` or changing the closing `</p>` to a line break.

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.json
> +          "hint": "",
Oops. Just forgot to fill these in.

```suggestion
          "label": "D1.X.10 Changes in beneficiary circumstances",
          "hint": "Select the frequency the plan reports changes in beneficiary circumstances to the state.",
```

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.schema.ts
> +  "dpi-7-o1": nested(
```suggestion
  "dpi-7a": nested(
```

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.schema.ts
> +  "dpi-7-o2": nested(
```suggestion
  "dpi-7b": nested(
```

2022-08-26 13:50 UTC, braxex commented on services/ui-src/src/forms/mcpar/dpi/dpi.schema.ts
> +  "dpi-7-o3": nested(
```suggestion
  "dpi-7c": nested(
```

2022-08-26 20:56 UTC, braxex approved these changes

2022-08-26 21:04 UTC, merged