Add mixed number input
CMSgov/mdct-mcr pull request #3667
Opened 2022-08-30 15:41 UTC by ntsummers1

## Description
Sometimes the number you've reached just can't be gotten ahold of.

### How to test
./dev local
Create a report in the dashboard
Go to the test page
Play with the optional number input!

### Changed Dependencies

## Code author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [ ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-08-30 16:59 UTC, braxex commented on services/ui-src/src/verbiage/errors.ts
> +  INVALID_PERCENTAGE: "Please input a Number OR 'N/A'",
```suggestion
  INVALID_PERCENTAGE: "Response must be a valid number OR \"N/A\"",
```

2022-08-30 17:02 UTC, braxex commented on services/ui-src/src/utils/forms/schemas.ts
> +    .typeError("Please input a Number OR 'N/A'");
```suggestion
    .typeError(error.INVALID_NUMBER_OR_NA);
```

2022-08-30 17:04 UTC, braxex commented on services/ui-src/src/utils/forms/schemas.ts
> +}
Two thoughts:
  1. Not sure if we're going to be passing `null` here or `N/A`, but we'll figure this out.
  2. I think we might need to accept more than just `N/A` (for instance `N/A`, `n/a`, `Not applicable`, etc.). Maybe the `originalValue === "N/A"` check becomes a `.includes` check against an array of valid not-applicable-adjacent answers? Should prob build this way to future-proof.

2022-09-01 13:19 UTC, gmrabian requested changes
Help me out if I'm missing something:
I created my own number field and it allowed any text.
<img width="585" alt="Screen Shot 2022-09-01 at 7 19 23 AM" src="https://user-images.githubusercontent.com/57802560/187923864-2e975bc2-aa4f-46fe-b22e-63ed3dba5333.png">

2022-09-01 15:58 UTC, gmrabian approved these changes

2022-09-02 02:36 UTC, braxex approved these changes
Looks awesome. Only one tweak. 👍

2022-09-02 02:36 UTC, braxex commented on services/ui-src/src/verbiage/errors.ts
> +  INVALID_NUMBER_OR_NA: 'Response must be a valid number OR "N/A"',
```suggestion
  INVALID_NUMBER_OR_NA: 'Response must be a valid number or "N/A"',
```

2022-09-06 22:20 UTC, merged