Disable forms for admins
CMSgov/mdct-mcr pull request #3835
Opened 2022-09-08 19:23 UTC by britt-mo

## Description

Disable report fields for admin users

### How to test

log in as an admin and see that the report fields are disabled (including nested fields), and report fields for state users are not disabled.

### Changed Dependencies

## Code author checklist
- [x] I have performed a self-review of my code
- [x] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] ~~I have added analytics, if necessary~~
- [ ] ~~I have updated the documentation, if necessary~~

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-09-09 14:48 UTC, braxex requested changes
Looks good! There are a couple things yet to do but we're getting close:

1. Dynamic fields (see form `aap` or `absse`) aren't disabled. This is because the props aren't getting fully passed down into the TextField components that are rendered. Adding `{...props}` to line 40 of `DynamicField` should do the trick.
2. Validation is still running on the forms when admin users click 'Save & continue'. We should stop that from happening. Probably the easiest way is when constructing the form in Form.tsx, we could conditionally tell it if the form needs validation or not by passing the resolver something like this:
```
  const form = useForm({
    resolver: !shouldDisableAllFields ? yupResolver(formSchema) : undefined,
```
3. The 'Save and continue' button probably shouldn't say that anyway. Maybe just 'Continue' if the form is disabled. Would need to modify this in ReportPage.

2022-09-09 14:48 UTC, braxex commented on services/ui-src/src/forms/mcpar/index.ts
> +  copyAdminDisabledStatusToForms(rawReportJson);
Nit: Would maybe name this something like `reportJsonWithDisabledStatus` instead.
```suggestion
const reportJsonWithDisabledStatus: ReportJson =
  copyAdminDisabledStatusToForms(rawReportJson);
```

2022-09-09 14:48 UTC, braxex commented on services/ui-src/src/utils/reports/reports.test.ts
> +  const newReportJson: ReportJson = {
We actually have some mockReportJson available [here in setupJest.tsx](https://github.com/CMSgov/mdct-mcr/blob/ddb762731824513e0bd8a78e977c475709a4d036/services/ui-src/src/utils/testing/setupJest.tsx#L230-L235) you could use.

2022-09-09 14:49 UTC, braxex commented on services/ui-src/src/components/forms/Form.tsx
> +
Nit: Would maybe rename this something like `formInputDisabled` or `fieldInputDisabled` or something so when we use it below to determine if a resolver is set it reads a bit better.

2022-09-12 14:24 UTC, ntsummers1 approved these changes
Nice work! I wasn't able to break anything on this and the codes looking good.

2022-09-12 14:46 UTC, gmrabian requested changes
Looks like the dynamic field delete button still showed up for admin, and I was able to delete fields. It doesn't actually remove them from the database, and they show up the next time you enter the form. But we should not allow this to be here even so

<img width="591" alt="Screen Shot 2022-09-12 at 8 44 52 AM" src="https://user-images.githubusercontent.com/57802560/189684563-caee570b-00d0-4006-9c04-fb2d44f8aab2.png">



<img width="587" alt="Screen Shot 2022-09-12 at 8 44 56 AM" src="https://user-images.githubusercontent.com/57802560/189684306-7e3bb333-bc1a-4f71-a640-16acd0e767a2.png">

2022-09-12 18:12 UTC, ntsummers1 approved these changes

2022-09-12 18:12 UTC, ntsummers1 commented
Garretts callout seems fixed. Looks great on my end

2022-09-13 13:16 UTC, gmrabian approved these changes
looks good!

2022-09-13 15:59 UTC, gmrabian approved these changes

2022-09-13 16:42 UTC, merged