MDCT-2016: Section C Redlines
CMSgov/mdct-mcr pull request #4253
Opened 2022-10-06 17:04 UTC by ntsummers1

## Description
Full list of changes here: [MDCT-2016](https://qmacbis.atlassian.net/browse/MDCT-2016)

### How to test
./dev local
Load up a program
Checkout section C!

### Changed Dependencies

## Code author checklist
- [x] I have performed a self-review of my code
- [x] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [x] I have added analytics, if necessary
- [x] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-10-06 22:35 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "label": "Other, specify",
Because this changed, the `"visibleOptionValue": "Other"` on line 745 also needs to be updated.

2022-10-06 22:41 UTC, braxex requested changes
Looking good. Just a couple changes requested.

2022-10-06 22:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                      "label": "Other, specify",
Request: Because this changed, the "visibleOptionValue": "Other" on line 800 also needs to be updated.

2022-10-06 22:41 UTC, braxex commented on services/ui-src/src/forms/mcpar/mcpar.json
> +                  "hint": "Describe the types of incentives that may be awarded to managed care plans for encounter data quality. Reply with N/A if the plan does not use incentives to award encounter
Nit: I know it wasn't requested, but let's add `""` around N/A for consistency with other cases.

2022-10-11 18:31 UTC, ntsummers1 commented
Approved by Kim!

2022-10-11 18:53 UTC, britt-mo approved these changes

2022-10-11 19:08 UTC, karla-vm approved these changes

2022-10-11 19:59 UTC, merged