Mdct 1907
CMSgov/mdct-mcr pull request #4426
Opened 2022-10-13 20:34 UTC by britt-mo

## Description

Integration test for state user creating, editing, and entering a program

### How to test
n/a

### Changed Dependencies
n/a

## Code author checklist
- [ x] I have performed a self-review of my code
- [x ] I have added [thorough](https://bit.ly/3zPrxuZ) tests
- [ ] I have added analytics, if necessary
- [x ] I have updated the documentation, if necessary

## Reviewer checklist (two different people)
- [ ] I have done the deep review and verified the items in the above checklist are g2g
- [ ] I have done the lgtm review

2022-10-13 20:38 UTC, BearHanded requested changes

2022-10-13 20:38 UTC, BearHanded commented on package.json
> +    "dynamodb-admin": "^4.4.1"
I think this can just be a devDependency, right?

2022-10-13 20:47 UTC, BearHanded approved these changes
Looks good, and we'll know if the integration test passes momentarily

2022-10-17 19:48 UTC, britt-mo commented
made a new PR for this

2022-10-17 19:48 UTC, closed without merging